packages:
  - name: api
    environment:
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      JWT_SECRET: ${JWT_SECRET}
    functions:
      - name: create-multipart
        runtime: nodejs:18
        web: true
      - name: sign-part
        runtime: nodejs:18
        web: true
      - name: complete-multipart
        runtime: nodejs:18
        web: true
      - name: abort-multipart
        runtime: nodejs:18
        web: true
      - name: list-parts
        runtime: nodejs:18
        web: true
      - name: get-upload-url
        runtime: nodejs:18
        web: true
      - name: create-metadata
        runtime: nodejs:18
        web: true
      - name: get-metadata
        runtime: nodejs:18
        web: true
      - name: get-download-url
        runtime: nodejs:18
        web: true
      - name: delete-file
        runtime: nodejs:18
        web: true
      - name: list-files
        runtime: nodejs:18
        web: true 